spring.application.name=waterwise
# PostgreSQL-anslutning
spring.datasource.url=jdbc:postgresql://localhost:5432/waterwise
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Kör SQL-filerna vid start
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:tables.sql,classpath:views.sql
spring.sql.init.data-locations=classpath:inserts.sql

# SQL-filerna ansvarar för tabellerna
spring.jpa.hibernate.ddl-auto=none

# Visar SQL i konsolen
spring.jpa.show-sql=true
